services:

  mysql:
    image: mysql:8.4
    container_name: dj-events-mysql

    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: Bangi131193
      MYSQL_DATABASE: dj_events

    ports:
      - "3307:3306"

    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: